// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { IssuesReadIssuesData, IssuesReadIssuesResponse, IssuesCreateIssueData, IssuesCreateIssueResponse, IssuesReadCalendarIssuesData, IssuesReadCalendarIssuesResponse, IssuesReadIssueData, IssuesReadIssueResponse, IssuesUpdateIssueData, IssuesUpdateIssueResponse, IssuesDeleteIssueData, IssuesDeleteIssueResponse, IssuesReadCommentsData, IssuesReadCommentsResponse, IssuesCreateCommentData, IssuesCreateCommentResponse, IssuesReadSharesData, IssuesReadSharesResponse, IssuesCreateShareData, IssuesCreateShareResponse, IssuesDeleteShareData, IssuesDeleteShareResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersLookupUserByEmailData, UsersLookupUserByEmailResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class IssuesService {
    /**
     * Read Issues
     * Retrieve issues owned by, or shared with, the current user.
     * Superusers see all issues.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.status
     * @param data.priority
     * @param data.assigneeId
     * @returns IssuesPublic Successful Response
     * @throws ApiError
     */
    public static readIssues(data: IssuesReadIssuesData = {}): CancelablePromise<IssuesReadIssuesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/issues/',
            query: {
                skip: data.skip,
                limit: data.limit,
                status: data.status,
                priority: data.priority,
                assignee_id: data.assigneeId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create Issue
     * Create a new issue.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns IssuePublic Successful Response
     * @throws ApiError
     */
    public static createIssue(data: IssuesCreateIssueData): CancelablePromise<IssuesCreateIssueResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/issues/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Calendar Issues
     * Retrieve visible issues with due dates inside an inclusive date range.
     * @param data The data for the request.
     * @param data.start
     * @param data.end
     * @returns IssuesPublic Successful Response
     * @throws ApiError
     */
    public static readCalendarIssues(data: IssuesReadCalendarIssuesData): CancelablePromise<IssuesReadCalendarIssuesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/issues/calendar',
            query: {
                start: data.start,
                end: data.end
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Issue
     * Get issue by ID, including the current user's permissions on it.
     * @param data The data for the request.
     * @param data.id
     * @returns IssueDetailPublic Successful Response
     * @throws ApiError
     */
    public static readIssue(data: IssuesReadIssueData): CancelablePromise<IssuesReadIssueResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/issues/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Issue
     * Update an issue.
     *
     * The owner (or a superuser) may change any field. A user the issue was
     * shared with may only change `status` (if granted) and/or `assignee_id`
     * (if granted); any other field in the request is rejected.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns IssuePublic Successful Response
     * @throws ApiError
     */
    public static updateIssue(data: IssuesUpdateIssueData): CancelablePromise<IssuesUpdateIssueResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/issues/{id}',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete Issue
     * Delete an issue. Owner or superuser only.
     * @param data The data for the request.
     * @param data.id
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteIssue(data: IssuesDeleteIssueData): CancelablePromise<IssuesDeleteIssueResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/issues/{id}',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Comments
     * List comments on an issue. Requires owner, shared, or superuser access.
     * @param data The data for the request.
     * @param data.id
     * @returns CommentsPublic Successful Response
     * @throws ApiError
     */
    public static readComments(data: IssuesReadCommentsData): CancelablePromise<IssuesReadCommentsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/issues/{id}/comments',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create Comment
     * Add a comment to an issue. Requires owner, shared, or superuser access.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns CommentPublic Successful Response
     * @throws ApiError
     */
    public static createComment(data: IssuesCreateCommentData): CancelablePromise<IssuesCreateCommentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/issues/{id}/comments',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read Shares
     * List the users an issue is shared with. Owner or superuser only.
     * @param data The data for the request.
     * @param data.id
     * @returns IssueSharesPublic Successful Response
     * @throws ApiError
     */
    public static readShares(data: IssuesReadSharesData): CancelablePromise<IssuesReadSharesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/issues/{id}/shares',
            path: {
                id: data.id
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create Share
     * Share an issue with another user by email. Owner or superuser only.
     * @param data The data for the request.
     * @param data.id
     * @param data.requestBody
     * @returns IssueSharePublic Successful Response
     * @throws ApiError
     */
    public static createShare(data: IssuesCreateShareData): CancelablePromise<IssuesCreateShareResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/issues/{id}/shares',
            path: {
                id: data.id
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete Share
     * Revoke a user's access to a shared issue. Owner or superuser only.
     * @param data The data for the request.
     * @param data.id
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteShare(data: IssuesDeleteShareData): CancelablePromise<IssuesDeleteShareResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/issues/{id}/shares/{user_id}',
            path: {
                id: data.id,
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }

    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }

    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }

    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Lookup User By Email
     * Look up a user by email. Available to any authenticated user so an
     * issue's owner can find a user to assign or share the issue with.
     * @param data The data for the request.
     * @param data.email
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static lookupUserByEmail(data: UsersLookupUserByEmailData): CancelablePromise<UsersLookupUserByEmailResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/lookup',
            query: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }

    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}
