// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CommentCreate = {
    content: string;
};

export type CommentPublic = {
    id: string;
    issue_id: string;
    author_id: string;
    author_email: string;
    content: string;
    created_at?: (string | null);
};

export type CommentsPublic = {
    data: Array<CommentPublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type IssueCreate = {
    title: string;
    description?: (string | null);
    status?: IssueStatus;
    priority?: number;
    assignee_id?: (string | null);
};

export type IssueDetailPublic = {
    title: string;
    description?: (string | null);
    status?: IssueStatus;
    priority?: number;
    id: string;
    owner_id: string;
    owner_email: string;
    assignee_id: (string | null);
    assignee_email: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
    is_owner: boolean;
    can_edit_status: boolean;
    can_edit_assignee: boolean;
};

export type IssuePublic = {
    title: string;
    description?: (string | null);
    status?: IssueStatus;
    priority?: number;
    id: string;
    owner_id: string;
    owner_email: string;
    assignee_id: (string | null);
    assignee_email: (string | null);
    created_at?: (string | null);
    updated_at?: (string | null);
};

export type IssuesPublic = {
    data: Array<IssuePublic>;
    count: number;
};

export type IssueShareCreate = {
    email: string;
    can_edit_status?: boolean;
    can_edit_assignee?: boolean;
};

export type IssueSharePublic = {
    id: string;
    issue_id: string;
    user_id: string;
    user_email: string;
    can_edit_status: boolean;
    can_edit_assignee: boolean;
};

export type IssueSharesPublic = {
    data: Array<IssueSharePublic>;
};

export type IssueStatus = 'Open' | 'In Progress' | 'Done';

export type IssueUpdate = {
    title?: (string | null);
    description?: (string | null);
    status?: (IssueStatus | null);
    priority?: (number | null);
    assignee_id?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type IssuesReadIssuesData = {
    assigneeId?: (string | null);
    limit?: number;
    priority?: (number | null);
    skip?: number;
    status?: (IssueStatus | null);
};

export type IssuesReadIssuesResponse = (IssuesPublic);

export type IssuesCreateIssueData = {
    requestBody: IssueCreate;
};

export type IssuesCreateIssueResponse = (IssuePublic);

export type IssuesReadIssueData = {
    id: string;
};

export type IssuesReadIssueResponse = (IssueDetailPublic);

export type IssuesUpdateIssueData = {
    id: string;
    requestBody: IssueUpdate;
};

export type IssuesUpdateIssueResponse = (IssuePublic);

export type IssuesDeleteIssueData = {
    id: string;
};

export type IssuesDeleteIssueResponse = (Message);

export type IssuesReadCommentsData = {
    id: string;
};

export type IssuesReadCommentsResponse = (CommentsPublic);

export type IssuesCreateCommentData = {
    id: string;
    requestBody: CommentCreate;
};

export type IssuesCreateCommentResponse = (CommentPublic);

export type IssuesReadSharesData = {
    id: string;
};

export type IssuesReadSharesResponse = (IssueSharesPublic);

export type IssuesCreateShareData = {
    id: string;
    requestBody: IssueShareCreate;
};

export type IssuesCreateShareResponse = (IssueSharePublic);

export type IssuesDeleteShareData = {
    id: string;
    userId: string;
};

export type IssuesDeleteShareResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersLookupUserByEmailData = {
    email: string;
};

export type UsersLookupUserByEmailResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);
